var searchAutocompleteWeightedKeywords=window.searchAutocompleteWeightedKeywords||{};var searchAutocompleteKeywords=window.searchAutocompleteKeywords||[];var searchAutocompleteWords=window.searchAutocompleteWords||[];var searchAutocompletePhrases=window.searchAutocompletePhrases||[];function arrayIndexOf(arr,val){for(var i=0;i<arr.length;i++)if(arr[i]===val)return i;return-1}var wordSeparator=/\s+/;function getWords(s){return s.trim().split(wordSeparator)}
function getWordsLowercase(s){return s.trim().toLowerCase().split(wordSeparator)}
function keywordMatch(term,keyword){if(term==="")return false;var keywordWordsOriginalCase=getWords(keyword);var keywordWords=getWordsLowercase(keyword);var termWords=getWordsLowercase(term);var termIncomplete=null;if(term[term.length-1]!==" "){termIncomplete=termWords[termWords.length-1];termWords=termWords.slice(0,termWords.length-1)}var matched=[];var mismatched=[];var newTerm=[];for(var i=0;i<termWords.length;i++){var idx=arrayIndexOf(keywordWords,termWords[i]);if(idx!==-1){matched.push(termWords[i]);
newTerm.push(keywordWordsOriginalCase[idx])}else{mismatched.push(termWords[i]);newTerm.push(termWords[i])}}if(termIncomplete!==null)for(var i=0;i<keywordWords.length;i++){var keywordWord=keywordWords[i];if(keywordWord.startsWith(termIncomplete)){matched+=termIncomplete.length/keywordWord.length;for(var j=i;j<keywordWords.length;j++)newTerm.push(keywordWordsOriginalCase[j])}else mismatched.push(keywordWord)}if(newTerm.length===1)newTerm=keywordWords;var allTermWords=termWords.length+(termIncomplete?
1:0);return{"matched":matched,"mismatched":mismatched.length,"termWords":allTermWords,"spareWords":keywordWords.length-allTermWords,"newTerm":newTerm}}(function(){for(var k in searchAutocompleteWeightedKeywords)if(arrayIndexOf(searchAutocompleteKeywords,k)===-1)searchAutocompleteKeywords.push(k)})();
(function(){var seen={};searchAutocompleteWords.forEach(function(word){seen[word]=true});searchAutocompleteKeywords.forEach(function(keyword){getWordsLowercase(keyword).forEach(function(word){if(seen[word])return;seen[word]=true;searchAutocompleteWords.push(word)})})})();function getTermWeight(term,weightMap){if(weightMap&&weightMap.hasOwnProperty(term))return weightMap[term];return searchAutocompleteWeightedKeywords.hasOwnProperty(term)?searchAutocompleteWeightedKeywords[term]:1}
function getAutocompleteKeywordsForTerm(term){if(term==="")return[];var termWords=getWordsLowercase(term);var filtered=termWords.join(" ");var result=[];var rmap={};searchAutocompletePhrases.forEach(function(phrase){if(phrase===filtered)return;var match=keywordMatch(term,phrase);if(match===false||match.matched.length===0||match.mismatched>match.spareWords)return;var keyword=match.newTerm.join(" ").toLowerCase();if(rmap[keyword]!==undefined)return;result.push(keyword);rmap[keyword]=-1+getTermWeight(keyword)});
searchAutocompleteKeywords.forEach(function(keyword){if(keyword!==filtered&&keyword.startsWith(filtered)){result.push(keyword);rmap[keyword]=getTermWeight(keyword)}});searchAutocompleteKeywords.forEach(function(keyword){if(rmap[keyword]!==undefined||keyword===filtered)return;var words=getWordsLowercase(keyword);for(var j=0;j<termWords.length;j++){var found=false;for(var i=0;i<words.length&&!found;i++)if(termWords[j]===words[i]||term[term.length-1]!==" "&&j===termWords.length-1&&words[i].startsWith(termWords[j]))found=
true;if(!found)return}var match=keywordMatch(term,keyword);if(match===false||match.matched.length===0||match.mismatched>match.spareWords)return;result.push(keyword);rmap[keyword]=getTermWeight(keyword);console.log(keyword)});if(termWords.length>0){var lastWord=termWords[termWords.length-1];var tterm=term.trimRight();var prefix=tterm.substring(0,tterm.length-lastWord.length);searchAutocompleteWords.forEach(function(word){if(rmap[prefix+word]!==undefined)return;if(arrayIndexOf(termWords,word)!==-1)return;
if(word.startsWith(lastWord))result.push(prefix+word)})}result.sort(function(a,b){var weightA=getTermWeight(a,rmap);var weightB=getTermWeight(b,rmap);if(weightA!==weightB)return weightB-weightA;return a===b?0:a<b?-1:1});return result};
